- repo: local
  hooks:
    - id: license-header-check
      name: license header check
      entry: license-eye header check
      language: system
      types: [file]
    - id: license-header-fix
      name: license header fix
      entry: license-eye header fix
      language: system
      types: [file]
