#===============================================================================
# Copyright 2014 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

##  Content:
##     oneAPI Data Analytics Library algorithms list
##******************************************************************************

CORE.ALGORITHMS.CUSTOM.AVAILABLE := low_order_moments covariance cosdistance cordistance kmeans pca cholesky            \
                svd qr em kernel_function normalization optimization_solver objective_function                          \
                dtrees/gbt dtrees/forest linear_regression ridge_regression                                             \
                svm multiclassclassifier k_nearest_neighbors logistic_regression implicit_als                           \
                coordinate_descent jaccard triangle_counting shortest_paths subgraph_isomorphism connected_components   \
                louvain tsne

classifier += classifier/inner
low_order_moments +=
covariance +=
cosdistance +=
cordistance += covariance
elastic_net += linear_model regression optimization_solver objective_function engines
kmeans += engines distributions
pca += pca/metrics pca/transform svd covariance low_order_moments normalization
cholesky +=
svd +=
qr +=
em += covariance engines distributions
kernel_function += kernel_function/polynomial
normalization += normalization/minmax normalization/zscore low_order_moments
optimization_solver += optimization_solver/lbfgs optimization_solver/coordinate_descent objective_function engines distributions
coordinate_descent += optimization_solver/coordinate_descent objective_function engines distributions
objective_function += objective_function/cross_entropy_loss objective_function/logistic_loss objective_function/mse
dtrees/gbt += dtrees dtrees/gbt/classification dtrees/gbt/regression engines classifier regression objective_function
dtrees/forest += dtrees dtrees/regression dtrees/forest/classification dtrees/forest/regression engines classifier regression distributions
linear_regression += linear_model regression
lasso_regression += linear_model regression optimization_solver objective_function engines
ridge_regression += linear_model regression
svm += classifier kernel_function multiclassclassifier
multiclassclassifier += classifier
k_nearest_neighbors += engines classifier
logistic_regression += classifier optimization_solver objective_function engines
implicit_als += engines distributions
engines += engines/mt19937 engines/mcg59 engines/mrg32k3a engines/philox4x32x10 engines/mt2203
distributions += distributions/bernoulli distributions/normal distributions/uniform
tsne +=

CORE.ALGORITHMS.FULL :=                                                       \
    cholesky                                                                  \
    classifier                                                                \
    cordistance                                                               \
    cosdistance                                                               \
    covariance                                                                \
    distributions                                                             \
    distributions/bernoulli                                                   \
    distributions/normal                                                      \
    distributions/uniform                                                     \
    dtrees                                                                    \
    dtrees/forest                                                             \
    dtrees/forest/classification                                              \
    dtrees/forest/regression                                                  \
    dtrees/gbt                                                                \
    dtrees/gbt/regression                                                     \
    dtrees/gbt/classification                                                 \
    dtrees/regression                                                         \
    dbscan                                                                    \
    elastic_net                                                               \
    engines                                                                   \
    engines/mcg59                                                             \
    engines/mrg32k3a                                                          \
    engines/philox4x32x10                                                     \
    engines/mt19937                                                           \
    engines/mt2203                                                            \
    em                                                                        \
    implicit_als                                                              \
    kernel_function                                                           \
    kernel_function/polynomial                                                \
    kmeans                                                                    \
    k_nearest_neighbors                                                       \
    lbfgs                                                                     \
    linear_model                                                              \
    lasso_regression                                                          \
    linear_regression                                                         \
    logistic_regression                                                       \
    low_order_moments                                                         \
    multiclassclassifier                                                      \
    normalization/minmax                                                      \
    normalization/zscore                                                      \
    objective_function                                                        \
    objective_function/cross_entropy_loss                                     \
    objective_function/logistic_loss                                          \
    objective_function/mse                                                    \
    optimization_solver                                                       \
    optimization_solver/lbfgs                                                 \
    optimization_solver/coordinate_descent                                    \
    pca                                                                       \
    pca/transform                                                             \
    pivoted_qr                                                                \
    qr                                                                        \
    regression                                                                \
    ridge_regression                                                          \
    svd                                                                       \
    svm                                                                       \
    tsne

CORE.ALGORITHMS := $(if $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.FULL))
CORE.ALGORITHMS := $(sort $(foreach alg,$(CORE.ALGORITHMS),$(foreach alg1,$($(alg)),$(foreach alg2,$($(alg1)),$($(alg2)) $(alg2)) $(alg1)) $(alg)))

CORE.ALGORITHMS.INC :=                                                        \
    cholesky                                                                  \
    classifier                                                                \
    covariance                                                                \
    decision_forest                                                           \
    distance                                                                  \
    distributions                                                             \
    dbscan                                                                    \
    elastic_net                                                               \
    engines                                                                   \
    em                                                                        \
    gradient_boosted_trees                                                    \
    implicit_als                                                              \
    kernel_function                                                           \
    kmeans                                                                    \
    k_nearest_neighbors                                                       \
    lasso_regression                                                          \
    linear_model                                                              \
    linear_regression                                                         \
    logistic_regression                                                       \
    moments                                                                   \
    multi_class_classifier                                                    \
    normalization                                                             \
    optimization_solver                                                       \
    optimization_solver/iterative_solver                                      \
    optimization_solver/lbfgs                                                 \
    optimization_solver/objective_function                                    \
    optimization_solver/precomputed                                           \
    optimization_solver/coordinate_descent                                    \
    pca                                                                       \
    pca/transform                                                             \
    pivoted_qr                                                                \
    qr                                                                        \
    regression                                                                \
    ridge_regression                                                          \
    svd                                                                       \
    svm                                                                       \
    tree_utils                                                                \
    tsne


CORE.SERVICES       := data_management

# Dependencies between oneAPI and core (CPU-only) algorithms
ONEAPI.ALGOS.basic_statistics := CORE.moments
ONEAPI.ALGOS.covariance    := CORE.covariance
ONEAPI.ALGOS.dbscan := CORE.dbscan
ONEAPI.ALGOS.decision_forest := CORE.decision_forest
ONEAPI.ALGOS.kmeans := CORE.kmeans
ONEAPI.ALGOS.kmeans_init := CORE.kmeans
ONEAPI.ALGOS.knn := CORE.k_nearest_neighbors
ONEAPI.ALGOS.linear_kernel := CORE.kernel_function
ONEAPI.ALGOS.objective_function := CORE.objective_function
ONEAPI.ALGOS.pca           := CORE.pca
ONEAPI.ALGOS.polynomial_kernel := CORE.kernel_function
ONEAPI.ALGOS.sigmoid_kernel := CORE.kernel_function
ONEAPI.ALGOS.rbf_kernel    := CORE.kernel_function
ONEAPI.ALGOS.svm           := CORE.svm

# List of algorithms in oneAPI part

ONEAPI.ALGOS :=          \
    basic_statistics     \
    chebyshev_distance   \
    correlation_distance \
    cosine_distance      \
    covariance           \
    dbscan               \
    decision_forest      \
    decision_tree        \
    finiteness_checker   \
    kmeans               \
    kmeans_init          \
    knn                  \
    linear_kernel        \
    linear_regression    \
    logistic_regression  \
    logloss_objective    \
    louvain              \
    newton_cg            \
    minkowski_distance   \
    objective_function   \
    pca                  \
    polynomial_kernel    \
    sigmoid_kernel       \
    rbf_kernel           \
    svm                  \
    jaccard              \
    triangle_counting    \
    shortest_paths       \
    subgraph_isomorphism \
    connected_components


ONEAPI.IO :=     \
    csv
