#===============================================================================
# Copyright contributors to the oneDAL project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

name: Check Intel URLs
on: 
  schedule:
    - cron: "0 0 * * 6"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write

jobs:
  check_download:
    strategy:
      fail-fast: false
      matrix:
        include:
          - MAIN_URL: "https://www.intel.com/content/www/us/en/developer/tools/oneapi/oneapi-toolkit-download.html"
            FILENAME: ".ci/pipeline/ci.yml"
            DEPENDENCY: "Basekit"
          - MAIN_URL: "https://www.intel.com/content/www/us/en/developer/articles/technical/intel-cpu-runtime-for-opencl-applications-with-sycl-support.html"
            FILENAME: ".ci/scripts/collect_opencl_rt.ps1"
            DEPENDENCY: "OpenCL"
    name: Windows_${{ matrix.DEPENDENCY }}
    if: github.repository == 'uxlfoundation/oneDAL'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Collect main URL
        run: |
          echo "main_exe=$(grep -oP -m 1  'https?://[^ ]+\.exe' ${{ matrix.FILENAME }})" >> $GITHUB_ENV
      - name: Query online URL
        run: |
          curl -L --retry 3 -o temp.html ${{ matrix.MAIN_URL }}
          QUERY_EXE=$(grep -oP 'https?://[^ "]+\.exe' temp.html | head -1)
          QUERY_VERSION=$(echo "$QUERY_EXE" | grep -oP '[\d.]+(?=(_offline)?\.exe)')
          echo "query_exe=$QUERY_EXE" >> $GITHUB_ENV
          echo "query_version=$QUERY_VERSION" >> $GITHUB_ENV
          echo "PR_BOOL=$(gh pr list --head ${{ matrix.DEPENDENCY }}/$QUERY_VERSION --state open --json number --jq 'length')" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Update PR
        if: ${{ env.main_exe != env.query_exe && env.PR_BOOL != '1' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b ${{ matrix.DEPENDENCY }}/${{ env.query_version }}
          sed -i 's|${{ env.main_exe }}|${{ env.query_exe }}|g' ${{ matrix.FILENAME }}
          git add ${{ matrix.FILENAME }}
          git commit -m "Update ${{ matrix.DEPENDENCY }} to ${{ env.query_version }}"
          git push origin ${{ matrix.DEPENDENCY }}/${{ env.query_version }}
          gh pr create --title "Update Windows ${{ matrix.DEPENDENCY }} to ${{ env.query_version }}" --body "autogenerated"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
